name: mama_kris
description: "MamaKris Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.3+37

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  email_validator: ^3.0.0
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.5
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  package_info_plus: 4.2.0
  font_awesome_flutter: ^10.7.0
  sign_in_with_apple: ^6.1.0
  flutter_local_notifications: ^17.2.3
  http: ^1.2.1
  flutter_inappwebview: ^6.1.5
  multi_select_flutter: ^4.1.3
  share_plus: ^10.0.2
  video_player: ^2.9.2
  webview_flutter: ^4.10.0
  flutter_kinescope_sdk: ^0.1.6
  shared_preferences: ^2.3.2
  in_app_review: ^2.0.10
  intl: ^0.20.0
  cupertino_icons: ^1.0.8
  build_runner: ^2.4.13
  go_router: ^16.2.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.1
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  flutter_slidable: ^4.0.1
  pinput: ^5.0.2
  fpdart: ^1.1.1
  dio: ^5.9.0
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_icons:
  image_path: "assets/icon/app_icon.png" # путь к твоему лого
  ios: true
  remove_alpha_ios: true # рекомендуется, т.к. иконки без прозрачности

flutter:
  assets:
    - assets/images/
    - assets/icon/
    - assets/json/


    - assets/welcome_screen/apple.png
    - assets/welcome_screen/google.png
    - assets/welcome_screen/apple.svg
    - assets/welcome_screen/google.svg
    - assets/welcome_screen/text1.svg
    - assets/welcome_screen/text2.svg
    - assets/welcome_screen/text3.svg
    - assets/welcome_screen/logo.svg
    - assets/welcome_screen/logo.png
    - assets/welcome_screen/login.png
    - assets/welcome_screen/registration.png
    - assets/welcome_screen/blur.png
    - assets/welcome_screen/arrow.png
    - assets/welcome_screen/arrow_green.png
    - assets/welcome_screen/arrow.svg
    - assets/welcome_screen/arrow_green.svg

    - assets/login_sheet/text.png
    - assets/login_sheet/text.svg

    - assets/register_contacts_sheet/text.svg

    - assets/register_confidentiality_sheet/text1.svg
    - assets/register_confidentiality_sheet/text2.svg

    - assets/checkbox/checked.svg
    - assets/checkbox/unchecked.svg
    - assets/checkbox/unchecked_radio.svg
    - assets/checkbox/checked_radio.svg

    - assets/role_sheet/text1.svg
    - assets/role_sheet/text2.svg

    - assets/monetization_screen/text1.svg
    - assets/monetization_screen/text2.svg

    - assets/bottom_bar/inactive/home.svg
    - assets/bottom_bar/inactive/orders.svg
    - assets/bottom_bar/inactive/chat.svg
    - assets/bottom_bar/inactive/profile.svg
    - assets/bottom_bar/active/home.svg
    - assets/bottom_bar/active/orders.svg
    - assets/bottom_bar/active/chat.svg
    - assets/bottom_bar/active/profile.svg

    - assets/career_sheet/title.svg
    - assets/career_sheet/description.svg

    - assets/psycho_sheet/title.svg
    - assets/psycho_sheet/description.svg

    - assets/monetization_banner_screen/title.svg
    - assets/monetization_banner_screen/description.svg

    - assets/conf_screen/title.svg
    - assets/conf_screen/description.png

    - assets/license_screen/title.svg
    - assets/license_screen/title.png
    - assets/license_screen/description.png

    - assets/chat/title.svg
    - assets/chat/chat.svg

    - assets/profile/title.svg
    - assets/profile/exit.svg

    - assets/banners_sheet/title.svg
    - assets/banners_sheet/description.svg

    - assets/favorite_screen/title.svg

    - assets/favorite_contacts_sheet/title.svg
    - assets/favorite_contacts_sheet/share.svg
    - assets/favorite_contacts_sheet/favorite.svg

    - assets/vacancies_screen/title.svg
    - assets/vacancies_screen/active.png
    - assets/vacancies_screen/inactive.png

    - assets/dropdown/inactive.svg
    - assets/dropdown/active.svg

    - assets/usage_screen/image1.svg
    - assets/usage_screen/image2.svg
    - assets/usage_screen/image3.svg
    - assets/usage_screen/image4.svg
    - assets/usage_screen/image5.svg
    - assets/usage_screen/image6.svg

  fonts:
    - family: Jost
      fonts:
        - asset: fonts/static/Jost-Thin.ttf
          weight: 100
        - asset: fonts/static/Jost-ExtraLight.ttf
          weight: 200
        - asset: fonts/static/Jost-Light.ttf
          weight: 300
        - asset: fonts/static/Jost-Regular.ttf
          weight: 400
        - asset: fonts/static/Jost-Medium.ttf
          weight: 500
        - asset: fonts/static/Jost-SemiBold.ttf
          weight: 600
        - asset: fonts/static/Jost-Bold.ttf
          weight: 700
        - asset: fonts/static/Jost-ExtraBold.ttf
          weight: 800
        - asset: fonts/static/Jost-Black.ttf
          weight: 900
        - asset: fonts/static/Jost-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/static/Jost-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/static/Jost-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/static/Jost-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/static/Jost-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/static/Jost-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/static/Jost-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/static/Jost-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/static/Jost-BlackItalic.ttf
          weight: 900
          style: italic

  uses-material-design: true
