name: mama_kris
description: "MamaKris Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.1.2+43

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^7.2.0
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  package_info_plus: ^9.0.0
  sign_in_with_apple: ^7.0.1
  flutter_local_notifications: ^19.4.2
  http: ^1.2.1
  flutter_inappwebview: ^6.1.5
  share_plus: ^12.0.1
  webview_flutter: ^4.10.0
  shared_preferences: ^2.3.2
  in_app_review: ^2.0.10
  intl: ^0.20.0
  cupertino_icons: ^1.0.8
  build_runner: ^2.4.13
  go_router: ^17.0.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.1
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  flutter_slidable: ^4.0.1
  pinput: ^6.0.1
  fpdart: ^1.1.1
  dio: ^5.9.0
  get_it: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  firebase_messaging: ^16.0.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.2
  cupertino_country_picker: ^1.0.4
  intl_phone_field: ^3.2.0
  auto_size_text: ^3.0.0
  freerasp: ^7.3.0
  flutter_svg: ^2.2.3
<<<<<<< HEAD
=======
  rename: ^3.1.0
  change_app_package_name: ^1.5.0
  get: ^4.7.3
<<<<<<< HEAD
>>>>>>> 4d0c480 (feat(support): add detailed support articles and update app configuration)
=======
>>>>>>> 4d0c480 (feat(support): add detailed support articles and update app configuration)

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png" # путь к твоему лого
  android: true
  ios: true
  remove_alpha_ios: true # рекомендуется, т.к. иконки без прозрачности

flutter:
  assets:
    - assets/images/
    - assets/icon/
    - shorebird.yaml

  fonts:
    - family: Jost
      fonts:
        - asset: fonts/static/Jost-Thin.ttf
          weight: 100
        - asset: fonts/static/Jost-ExtraLight.ttf
          weight: 200
        - asset: fonts/static/Jost-Light.ttf
          weight: 300
        - asset: fonts/static/Jost-Regular.ttf
          weight: 400
        - asset: fonts/static/Jost-Medium.ttf
          weight: 500
        - asset: fonts/static/Jost-SemiBold.ttf
          weight: 600
        - asset: fonts/static/Jost-Bold.ttf
          weight: 700
        - asset: fonts/static/Jost-ExtraBold.ttf
          weight: 800
        - asset: fonts/static/Jost-Black.ttf
          weight: 900
        - asset: fonts/static/Jost-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/static/Jost-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/static/Jost-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/static/Jost-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/static/Jost-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/static/Jost-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/static/Jost-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/static/Jost-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/static/Jost-BlackItalic.ttf
          weight: 900
          style: italic

  uses-material-design: true
